repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        stages: [commit]
        args: [ "--rcfile=pylint.cfg", "./app", "./test" ]

    -   id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [ python ]
        stages: [ commit ]
        args: [ "-r", "./app", "./test" ]

    -   id: unittest
        name: unittest
        entry: python -m unittest discover -s test -p "test_*.py"
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false